<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Contrasea_mdi mdi-eye mdi-24px</name>
   <tag></tag>
   <elementGuidId>dfac4453-efbb-4302-9176-de58abf541d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.mdi.mdi-eye.mdi-24px</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='app']/div/div/div/div/div/div/div/div/div[2]/div[2]/div/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-eye mdi-24px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@id=&quot;app&quot;]/section[1]/section[@id=&quot;app&quot;]/div[@class=&quot;columns is-gapless&quot;]/div[@class=&quot;column&quot;]/div[@class=&quot;content-app&quot;]/div[1]/div[@class=&quot;login&quot;]/div[@class=&quot;login-content&quot;]/div[1]/div[@class=&quot;login-component&quot;]/div[@class=&quot;login-content-inputs&quot;]/div[@class=&quot;field&quot;]/div[@class=&quot;control has-icons-right is-clearfix&quot;]/span[@class=&quot;icon is-right has-text-primary is-clickable&quot;]/i[@class=&quot;mdi mdi-eye mdi-24px&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='app']/div/div/div/div/div/div/div/div/div[2]/div[2]/div/span/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
   </webElementXpaths>
</WebElementEntity>
